# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'eloanLibDemo' do

pod 'eloanLib',:path => '../'
pod 'AliyunOSSiOS','2.10.8'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
